[package]
name = "plainsight_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
plainsight = { path = "../plainsight_lib" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }

tracing = "0.1.44"
